## Archetype
##
## Represents a unique combination of component types in the ECS framework.
## Entities with the exact same set of components share an archetype.
##
## Archetypes enable high-performance queries by grouping entities with identical
## component structures together in flat arrays, providing excellent cache locality
## and eliminating the need for set intersections during queries.
##
## [b]Key Concepts:[/b]
## - [b]Signature:[/b] Hash of all component types (determines archetype identity)
## - [b]Entities:[/b] Flat array of entities with this exact component combination
## - [b]Edges:[/b] Fast lookup for when components are added/removed (future optimization)
##
## [b]Example:[/b]
## [codeblock]
## # Archetype for entities with Position + Velocity
## var archetype = Archetype.new(12345, ["Position", "Velocity"])
## archetype.add_entity(player)
## archetype.add_entity(enemy)
## # Now both entities are stored contiguously for fast iteration
## [/codeblock]
##
## [b]Performance:[/b]
## - Add entity: O(1) amortized (array append)
## - Remove entity: O(1) (swap-remove with index tracking)
## - Query match: O(1) (check if archetype signature matches query)
## - Iterate entities: O(n) with excellent cache locality
class_name Archetype
extends RefCounted

## Unique hash identifying this component combination
## Generated by QueryCacheKey.build() from sorted component types
var signature: int = 0

## Array of component/relationship keys (ints for components, Strings for rel:// keys)
## Used for debugging and archetype matching logic
var component_types: Array = []

## Set view of component_types for O(1) membership tests in matches_query
var component_key_set: Dictionary = {}

## Subset of component_types containing only rel:// prefixed relationship slot keys
var relationship_types: Array = []

## Flat array of entities with this exact component combination
## Provides excellent cache locality when iterating in systems
var entities: Array[Entity] = []

## Fast lookup: Entity -> index in entities array
## Enables O(1) entity removal using swap-remove technique
var entity_to_index: Dictionary = {}  # Entity -> int

## OPTIMIZATION: Bitset for enabled/disabled state instead of archetype splitting
## Uses PackedInt64Array where each bit represents whether entity at that index is enabled
## Reduces archetype count by 2x and enables O(1) enabled/disabled filtering
var enabled_bitset: PackedInt64Array = []

## OPTIMIZATION: Structure of Arrays (SoA) column storage for cache-friendly iteration
## Maps script_instance_id (int) -> Array of component instances
## Enables Flecs-style direct array iteration without dictionary lookups
var columns: Dictionary = {}  # int (script_instance_id) -> Array of components

## Archetype edges for fast component add/remove
## Maps: Variant (int for components, String for relationships) -> Archetype
var add_edges: Dictionary = {}  # Variant (int|String) -> Archetype
var remove_edges: Dictionary = {}  # Variant (int|String) -> Archetype

## Reverse-edge tracking: which archetypes hold an add_edge or remove_edge pointing to this one.
## Keyed by source archetype instance_id for O(1) operations.
var neighbors: Dictionary = {}  # int (get_instance_id()) -> Archetype

## CHANGE DETECTION: monotonic global write clock shared by all archetypes
## (advanced by the World once per system run). Rows are stamped with this
## tick when written; queries with .changed() compare against a per-system
## baseline to skip archetypes/rows nothing wrote to.
static var global_change_tick: int = 1

## CHANGE DETECTION: per-row write versions, LAZILY allocated only for
## component keys some query tracks via .changed(). Parallel to entities.
var column_versions: Dictionary = {}  # int (comp_key) -> PackedInt64Array
## Highest write tick per tracked column — lets systems skip the whole
## archetype with one comparison when nothing in it changed.
var column_max_tick: Dictionary = {}  # int (comp_key) -> int


## Begin tracking write versions for a column (no-op when already tracked or
## the archetype lacks the column). Existing rows count as changed "now".
func ensure_change_tracking(comp_key: int) -> void:
	if column_versions.has(comp_key) or not columns.has(comp_key):
		return
	var versions := PackedInt64Array()
	versions.resize(entities.size())
	versions.fill(global_change_tick)
	column_versions[comp_key] = versions
	column_max_tick[comp_key] = global_change_tick


## Stamp one entity's row in a tracked column with the current global tick.
func mark_changed(comp_key: int, entity: Entity) -> void:
	var versions = column_versions.get(comp_key)
	if versions == null:
		return
	var index = entity_to_index.get(entity, -1)
	if index == -1:
		return
	versions[index] = global_change_tick
	column_versions[comp_key] = versions  # write back (PackedInt64Array is COW)
	column_max_tick[comp_key] = global_change_tick


## Entities whose row version in ANY of the listed tracked columns is newer
## than [param baseline]. Untracked columns count as always-changed (safe default).
func get_changed_entities(comp_keys: Array, baseline: int) -> Array[Entity]:
	# Hoist version arrays out of the row loop — no per-row dict lookups.
	var version_arrays: Array = []
	for ck in comp_keys:
		var v = column_versions.get(ck)
		if v == null:
			return entities.duplicate()  # untracked column: everything counts as changed
		version_arrays.append(v)
	var result: Array[Entity] = []
	var n := entities.size()
	if version_arrays.size() == 1:
		var v: PackedInt64Array = version_arrays[0]
		for i in n:
			if v[i] > baseline:
				result.append(entities[i])
	else:
		for i in n:
			for v in version_arrays:
				if v[i] > baseline:
					result.append(entities[i])
					break
	return result


## True when any listed column (or an untracked one) wrote after [param baseline].
func has_changes_since(comp_keys: Array, baseline: int) -> bool:
	for ck in comp_keys:
		if column_max_tick.get(ck, global_change_tick) > baseline:
			return true
	return false


## Initialize archetype with signature and component types
func _init(p_signature: int, p_component_types: Array):
	signature = p_signature
	component_types = p_component_types.duplicate()
	component_types.sort()  # Ensure sorted for consistent matching

	# Separate relationship slot keys (Strings) from component keys (ints)
	for comp_type in component_types:
		component_key_set[comp_type] = true
		if comp_type is String and comp_type.begins_with("rel://"):
			relationship_types.append(comp_type)
		else:
			# Only create columns for component keys, NOT relationship slots
			columns[comp_type] = []


## Add an entity to this archetype
## Uses O(1) append and tracks index for fast removal
## OPTIMIZATION: Also populates column arrays for cache-friendly iteration
func add_entity(entity: Entity) -> void:
	var index = entities.size()
	entities.append(entity)
	entity_to_index[entity] = index

	# OPTIMIZATION: Update enabled bitset
	_ensure_bitset_capacity(index + 1)
	_set_enabled_bit(index, entity.enabled)

	# OPTIMIZATION: Populate column arrays from entity.components
	# Iterate columns keys (skips rel:// keys which have no columns)
	for comp_key in columns:
		if entity.components.has(comp_key):
			columns[comp_key].append(entity.components[comp_key])
		else:
			# Entity doesn't have this component yet (might be mid-initialization)
			# Push null placeholder, will be fixed when component is added
			columns[comp_key].append(null)

	# CHANGE DETECTION: new rows count as changed "now" (FLECS semantics —
	# a system's first sight of an entity processes it)
	for comp_key in column_versions:
		var versions: PackedInt64Array = column_versions[comp_key]
		versions.append(global_change_tick)
		column_versions[comp_key] = versions
		column_max_tick[comp_key] = global_change_tick


## Remove an entity from this archetype using swap-remove
## O(1) operation: swaps with last entity and pops
## OPTIMIZATION: Also maintains column arrays in sync
func remove_entity(entity: Entity) -> bool:
	if not entity_to_index.has(entity):
		return false

	var index = entity_to_index[entity]
	var last_index = entities.size() - 1
	# The tail can hold dangling refs from entities freed outside
	# World.remove_entity (direct free()); the typed array refuses them on
	# write, which would leave this entity behind in its slot. Drop those rows
	# first, same as World.remove_entity does for the world entity list.
	while last_index > index and not is_instance_valid(entities[last_index]):
		entity_to_index.erase(entities[last_index])
		_pop_last_row()
		last_index -= 1

	# Swap with last element in entities array
	if index != last_index:
		var last_entity = entities[last_index]
		entities[index] = last_entity
		entity_to_index[last_entity] = index

		# OPTIMIZATION: Swap in column arrays too (maintain same ordering)
		for comp_key in columns:
			columns[comp_key][index] = columns[comp_key][last_index]

		# CHANGE DETECTION: keep version rows aligned through the swap
		for comp_key in column_versions:
			var versions: PackedInt64Array = column_versions[comp_key]
			versions[index] = versions[last_index]
			column_versions[comp_key] = versions

		# OPTIMIZATION: Swap enabled bit
		var last_enabled = _get_enabled_bit(last_index)
		_set_enabled_bit(index, last_enabled)

	entity_to_index.erase(entity)
	_pop_last_row()
	# OPTIMIZATION: bitset logical size follows entities.size(); the stale bit is
	# overwritten when a new entity is added.

	return true


## Drop the last row from the entity array, every component column and every
## change-tracking version column (they are kept index-aligned).
func _pop_last_row() -> void:
	entities.pop_back()
	for comp_key in columns:
		columns[comp_key].pop_back()
	for comp_key in column_versions:
		var versions: PackedInt64Array = column_versions[comp_key]
		versions.resize(versions.size() - 1)
		column_versions[comp_key] = versions


## Check if this archetype has a specific entity
func has_entity(entity: Entity) -> bool:
	return entity_to_index.has(entity)


## Get entity count in this archetype
func size() -> int:
	return entities.size()


## Check if archetype is empty
func is_empty() -> bool:
	return entities.is_empty()


## Clear all entities from this archetype
func clear() -> void:
	entities.clear()
	entity_to_index.clear()

	# OPTIMIZATION: Clear column arrays
	for comp_key in columns:
		columns[comp_key].clear()

	# OPTIMIZATION: Clear bitset
	enabled_bitset.clear()


## Check if this archetype matches a query with all/any/exclude components
## [param all_comp_types] Component paths that must all be present
## [param any_comp_types] Component paths where at least one must be present
## [param exclude_comp_types] Component paths that must not be present
func matches_query(all_comp_types: Array, any_comp_types: Array, exclude_comp_types: Array) -> bool:
	# Dictionary membership instead of Array.has linear scans — the miss path
	# tests every archetype against the query, so this is O(terms) not O(terms×types).
	# Check all_components: must have ALL of these
	for comp_type in all_comp_types:
		if not component_key_set.has(comp_type):
			return false

	# Check any_components: must have AT LEAST ONE of these
	if not any_comp_types.is_empty():
		var has_any = false
		for comp_type in any_comp_types:
			if component_key_set.has(comp_type):
				has_any = true
				break
		if not has_any:
			return false

	# Check exclude_components: must have NONE of these
	for comp_type in exclude_comp_types:
		if component_key_set.has(comp_type):
			return false

	return true


## Check if this archetype matches a relationship query with required/excluded rel keys
## [param required_rel_keys] Relationship slot keys that must all be present
## [param excluded_rel_keys] Relationship slot keys that must not be present
func matches_relationship_query(required_rel_keys: Array, excluded_rel_keys: Array) -> bool:
	# component_key_set contains rel:// slot keys too — O(1) membership.
	# Required entries may be a single slot key or an OR-group of compatible keys.
	for rel_key in required_rel_keys:
		if rel_key is Array:
			var has_any := false
			for candidate in rel_key:
				if component_key_set.has(candidate):
					has_any = true
					break
			if not has_any:
				return false
		elif not component_key_set.has(rel_key):
			return false

	# Excluded entries may also be OR-groups; any matching key excludes the archetype.
	for rel_key in excluded_rel_keys:
		if rel_key is Array:
			for candidate in rel_key:
				if component_key_set.has(candidate):
					return false
		elif component_key_set.has(rel_key):
			return false
	return true


## Get a debug-friendly string representation
func _to_string() -> String:
	var comp_names = []
	for comp_type in component_types:
		if comp_type is String:
			# Relationship slot key — extract readable name from path
			var parts = comp_type.split("/")
			var filename = parts[parts.size() - 1].replace(".gd", "")
			comp_names.append(filename)
		else:
			comp_names.append(str(comp_type))

	return (
		"Archetype[sig=%d, comps=%s, entities=%d]"
		% [
			signature,
			str(comp_names),
			entities.size(),
		]
	)


## Set up an edge to another archetype when a component is added
## Enables O(1) archetype transitions when components change
func set_add_edge(comp_key: Variant, target_archetype: Archetype) -> void:
	add_edges[comp_key] = target_archetype
	target_archetype.neighbors[get_instance_id()] = self


## Set up an edge to another archetype when a component is removed
## Enables O(1) archetype transitions when components change
func set_remove_edge(comp_key: Variant, target_archetype: Archetype) -> void:
	remove_edges[comp_key] = target_archetype
	target_archetype.neighbors[get_instance_id()] = self


## Get the target archetype when adding a component (if edge exists)
func get_add_edge(comp_key: Variant) -> Archetype:
	return add_edges.get(comp_key, null)


## Get the target archetype when removing a component (if edge exists)
func get_remove_edge(comp_key: Variant) -> Archetype:
	return remove_edges.get(comp_key, null)


## OPTIMIZATION: Get component column array for cache-friendly iteration
## Enables Flecs-style direct array access instead of dictionary lookups per entity
## [param comp_key] The component key (Script.get_instance_id()) or relationship slot key (String)
## [returns] Array of component instances in entity index order, or empty array if not found
##
## Example:
## [codeblock]
## var velocities = archetype.get_column(C_Velocity.get_instance_id())
## for i in range(velocities.size()):
##     var velocity = velocities[i]
##     var entity = archetype.entities[i]
##     # Process with cache-friendly sequential access
## [/codeblock]
func get_column(comp_key: Variant) -> Array:
	return columns.get(comp_key, [])


## OPTIMIZATION: Get entities filtered by enabled state using bitset
## [param enabled_only] If true, return only enabled entities; if false, only disabled
## [returns] Array of entities matching the enabled state
func get_entities_by_enabled_state(enabled_only: bool) -> Array[Entity]:
	var result: Array[Entity] = []
	for i in range(entities.size()):
		if _get_enabled_bit(i) == enabled_only:
			result.append(entities[i])
	return result


## OPTIMIZATION: Update entity enabled state in bitset
## [param entity] The entity to update
## [param enabled] The new enabled state
func update_entity_enabled_state(entity: Entity, enabled: bool) -> void:
	if entity_to_index.has(entity):
		var index = entity_to_index[entity]
		_set_enabled_bit(index, enabled)


## OPTIMIZATION: Ensure bitset has enough capacity for the given number of entities
func _ensure_bitset_capacity(required_size: int) -> void:
	var required_int64s = (required_size + 63) / 64  # Round up to nearest 64-bit boundary
	while enabled_bitset.size() < required_int64s:
		enabled_bitset.append(0)


## OPTIMIZATION: Set enabled bit for entity at index
func _set_enabled_bit(index: int, enabled: bool) -> void:
	var int64_index = index / 64
	var bit_index = index % 64

	_ensure_bitset_capacity(index + 1)

	if enabled:
		enabled_bitset[int64_index] |= (1 << bit_index)
	else:
		enabled_bitset[int64_index] &= ~(1 << bit_index)


## OPTIMIZATION: Get enabled bit for entity at index
func _get_enabled_bit(index: int) -> bool:
	if index >= entities.size():
		return false

	var int64_index = index / 64
	var bit_index = index % 64

	if int64_index >= enabled_bitset.size():
		return false

	return (enabled_bitset[int64_index] & (1 << bit_index)) != 0
